development:
  adapter: postgresql
  database: jgarrettblog_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: jgarrettblog_test
  pool: 5
  timeout: 5000
  host: localhost
  port: 5433

production:
  adapter: postgresql
  database: jgarrettblog_production
  pool: 5
  timeout: 5000